[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "py-scheme"
version = "0.0.1"
description = "Minimal r7rs scheme python library with a repl. Made by gpt, tuned by a human."
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
